function cr=eye_find_cr(e, l, c)
%  eye_find_cr  Finds the position of a corneal reflex
%    cr = eye_find_cr(e, l, c) finds the position of the corneal reflex
%    generated by light 'l' on the eye 'e' as seen by the camera 'c', i.e. it
%    determines the point 'cr' on the surface of the cornea where a ray
%    emanating from 'l' will be reflected directly onto 'c'. If the reflex did
%    not fall within the cornea, [] is returned.

%    Copyright 2008 Martin Böhme and the University of Lübeck
%
%    This file is part of et_simul.
%
%    et_simul is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License (version 3) as
%    published by the Free Software Foundation.
%
%    et_simul is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    (version 3) along with et_simul in a file called 'COPYING'. If not, see
%    <http://www.gnu.org/licenses/>.

    cr=find_reflection(l.pos, c.trans(:,4), e.trans*e.pos_cornea, e.r_cornea);

    % Did the CR fall outside the border of the cornea?
    if ~eye_point_within_cornea(e, cr)
        cr=[];
    end
